# Generated by Django 5.1.4 on 2025-01-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
    ]
